apiVersion: v2
name: demo-e2e
description: Demo app + E2E tests
type: application
version: 0.1.0

dependencies:
  - name: greeting-app
    version: 0.1.0
    repository: file://greeting-app
  - name: e2e-tests
    version: 0.1.0
    repository: file://e2e-tests
